### PR TITLE
Use a more standard license file name

### PR DESCRIPTION
**Pull request by maxdeviant**
This will make the license file more compatible with tools that programatically pull the license text for all dependencies.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Why not just fix the broken tools?

**Comment by maxdeviant** [comment]
@mathiasbynens That is a possibility, but it seems like dealing with a one-off case. I haven't seen any other libraries that use this particular license file naming convention.

I am just relying on the informal standardization that npm has provided: [package.json#files](https://docs.npmjs.com/files/package.json#files).

**Comment by mathiasbynens** [comment]
`LICENSE*` seems easy enough to support in such tools. GitHub supports this file name format too for its new license UI: https://github.com/mathiasbynens/base64/blob/master/LICENSE-MIT.txt

**Comment by maxdeviant** [comment]
@mathiasbynens Ah yes, I did notice that.

Alright, I'll make the changes on our end. Thanks for your time.

**Pull request closed without merging**
